export const FETCH_REPO = "FETCH_REPO";
export const FETCH_REPO_SUCCESS = "FETCH_REPO_SUCCESS";
export const FETCH_REPO_FAILURE = "FETCH_REPO_FAILURE";
export const SET_TIME = "SET_TIME";
export const SET_LOADING = "SET_LOADING";
